### ISSUE TITLE
Current npm version is not compatible with Linux

### ISSUE THREAD

**Issue by nholland94** [ameyms/diffract#8]
The current version pushed up to npm only works on case insensitive filesystems (OSX/BSD) because it tries to import 'axis.js' when the file is 'Axis.js'. I see this has been fixed in this repo. Is there anyway you can push up a new version to npm?

**Comment by cdownard** [comment]
Bump!

**Comment by cdownard** [comment]
@ameyms ^

**Comment by ameyms** [comment]
Thanks for pointing this out! 
Will push a new version tonight

**Comment by cdownard** [comment]
Thanks so much!

**Comment by cdownard** [comment]
@ameyms did you push to npm last night? I don't see a new release there yet.

**Comment by ameyms** [comment]
Sorry about that. I ran into some problems with my local build last night.
Since I can't use my work laptop for this, could you please wait for
another day? Thanks for your patience.

**Comment by ameyms** [comment]
Should be fixed in v0.1.1.
Thanks again (for your patience and for pointing it out!), @nholland94 and @cdownard!
